feat: add boolop
vyperlang/titanoboa pull request #2
Opened 2022-06-28 15:28 UTC by tserg

**What I did**
- Handle `BoolOp` nodes in a similar fashion to `BinOp`.

2022-06-28 15:35 UTC, charles-cooper requested changes
nice start! i think we need short circuiting semantics -- only call `interpret()` if the parent nodes return false

2022-06-28 15:58 UTC, tserg commented
> nice start! i think we need short circuiting semantics -- only call `interpret()` if the parent nodes return false

False for `or` and True for `and`?

2022-06-28 16:29 UTC, charles-cooper commented
> > nice start! i think we need short circuiting semantics -- only call `interpret()` if the parent nodes return false
> 
> False for `or` and True for `and`?

ah, right

2022-06-29 02:43 UTC, charles-cooper approved these changes

2022-06-29 02:43 UTC, merged