feat: add contract verify on blockscout and etherscan
vyperlang/titanoboa pull request #303
Opened 2024-09-06 08:51 UTC by developerfred

ref #267

### What I did

I implemented a robust contract verification feature for the Boa framework, enabling seamless verification of deployed smart contracts on both Blockscout and Etherscan explorers. This enhancement significantly augments the developer experience by automating the often cumbersome process of contract verification, thus ensuring transparency and facilitating easier auditing of on-chain code.

### How I did it

The implementation was meticulously crafted through the following steps:

1. Developed a `ContractVerifier` class that encapsulates the logic for interacting with block explorer APIs, supporting both Blockscout and Etherscan.
2. Integrated the verification process into the existing `VyperDeployer` class, allowing for verification to be initiated immediately post-deployment.
3. Extended the high-level `load` and `loads` functions in the Boa framework to accept optional `verify` and `explorer` parameters, providing a user-friendly interface for contract deployment with verification.
4. Implemented comprehensive error handling and reporting to ensure robust operation in various scenarios, including API failures and verification rejections.
5. Utilized environment variables for secure storage of API keys, adhering to best practices in sensitive data management.
6. Created detailed documentation, including API references and usage examples, to facilitate easy adoption of the new feature.

### How to verify it

To verify the efficacy of this new feature:

1. Ensure the appropriate environment variables (`BLOCKSCOUT_API_KEY` or `ETHERSCAN_API_KEY`) are set in your development environment.
2. Execute the provided test suite, which includes both unit tests and integration tests simulating various verification scenarios.
3. Manually deploy and verify a contract using the new API:
   ```python
   import boa
   contract = boa.loads(source_code,  explorer="blockscout")
   
    # Alternative deployment methodology utilizing the VyperDeployer directly.
    # This granular approach offers enhanced control over the deployment process,
    # potentially facilitating more nuanced configuration options.
    deployer = VyperDeployer(compiler_data, filename="contract.vy")
    contract = deployer.deploy( explorer="etherscan")
   
   ```
4. Check the output for confirmation of successful verification, and cross-reference with the specified block explorer to ensure the contract appears as verified.
5. Attempt verification with invalid credentials or on an unsupported explorer to confirm proper error handling.

### Description for the changelog

Added automated contract verification feature for Blockscout and Etherscan explorers:
- Seamless integration with existing deployment workflow
- Support for both high-level (boa.loads) and low-level (VyperDeployer) APIs
- Configurable through environment variables for API key management
- Comprehensive error handling and user feedback
- Extensive documentation and test coverage

### Cute Animal Picture

![Put a link to a cute animal picture inside the parenthesis-->](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.KKTsf3s2OnwadSB-AwYAFQHaE1%26pid%3DApi&f=1&ipt=3967374963b79874d46e083913491846994be56d59b44be4adaf7463a1a0ea34&ipo=images)

2024-09-06 11:47 UTC, DanielSchiavini reviewed
Awesome feature, this is going to be quite useful!

2024-09-06 11:47 UTC, DanielSchiavini commented on boa/contracts/vyper/vyper_contract.py
> +    def deploy(self, *args, verify: bool = False, explorer: Optional[str] = None, **kwargs):
We could coalesce both parameters into a single one - no need for a boolean - maybe even a list of explorers. Besides being more succinct and flexible, it allows us to delete the validation below.

2024-09-06 11:47 UTC, DanielSchiavini commented on boa/contracts/vyper/vyper_contract.py
> +class ContractVerifier:
imo this should be two separate functions (no need for a class) in a separate file. Maybe just add the functions to a dict so we can leverage a built-in KeyError for invalid explorer arguments like
```
contract_verifiers = {"etherscan": validate_etherscan, "blockscout": validate_blockscout}
```
but @charles-cooper might think different

2024-09-06 11:47 UTC, DanielSchiavini commented on boa/interpret.py
> +        if verify:
this code is repeated, why not just pass the arguments directly to deploy without (even just via the kwargs)

2024-09-06 11:47 UTC, DanielSchiavini commented on boa/contracts/vyper/vyper_contract.py
> +        if explorer.lower() == "blockscout":
no need to support upper case imo

2024-09-06 11:47 UTC, DanielSchiavini commented on boa/contracts/vyper/vyper_contract.py
> +        return result.get("status") == "1"
instead of returning a boolean, it would be better to just raise an error that includes the body returned by the explorer

2024-09-06 11:47 UTC, DanielSchiavini commented on tests/unitary/contracts/vyper/test_vyper_contract.py
> +@pytest.mark.skipif(not os.getenv("BLOCKSCOUT_API_KEY"), reason="BLOCKSCOUT_API_KEY not set")
In order to use API keys please move the test to the integration folder

2024-09-06 11:47 UTC, DanielSchiavini commented on tests/unitary/contracts/vyper/test_vyper_contract.py
> +    mock_response = MagicMock()
wait if we are mocking why do we need the API key?

2024-09-06 11:57 UTC, charles-cooper requested changes
sorry, this doesn't look at all how the API works. https://docs.blockscout.com/developer-support/verifying-a-smart-contract/blockscout-smart-contract-verification-api

did you test that this actually works? or maybe this is, as I suspect, LLM- produced code?

2024-09-06 12:00 UTC, developerfred commented
> https://docs.blockscout.com/developer-support/verifying-a-smart-contract/blockscout-smart-contract-verification-api

I will update and test locally

2024-09-06 15:48 UTC, developerfred commented
![Screenshot 2024-09-06 at 19 34 53](https://github.com/user-attachments/assets/71abebf5-0c0d-4e3d-9a20-ad91565bbfe9)

@charles-cooper @DanielSchiavini

2024-09-06 17:44 UTC, charles-cooper commented
> ![Screenshot 2024-09-06 at 19 34 53](https://private-user-images.githubusercontent.com/57037080/365228347-71abebf5-0c0d-4e3d-9a20-ad91565bbfe9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MzkxMzEsIm5iZiI6MTcyNTYzODgzMSwicGF0aCI6Ii81NzAzNzA4MC8zNjUyMjgzNDctNzFhYmViZjUtMGMwZC00ZTNkLTlhMjAtYWQ5MTU2NWJiZmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE2MDcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMjk0MzAzMDZjNDQ0NmU5ODdkZDhkYjNjYThhYzNiMGNjNGFiNGFkNjg0MjVhNjY0YTE5NTJlODkwNzVlNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zq6Vv6DtchLqo1qChpoR7upmPpPZ-MYeFbk91Ubx_Mg)
> 
> @charles-cooper @DanielSchiavini

![Screenshot_20240906_180258_Brave](https://github.com/user-attachments/assets/418990ba-7d11-4c25-8006-d4a174a4e9e9)

Did you just take a screenshot of it passing the mock tests?

2024-09-06 18:04 UTC, developerfred commented
yeah, I can make a video too with a contract implemented and verified on the sepolia network

2024-09-08 11:22 UTC, developerfred commented
@charles-cooper  Do you think we should create a list of pre-networks available for verification, for example optimism, polygon, sepolia or is this implicit for the developer?

2024-09-26 16:43 UTC, closed without merging